# Generated by Django 5.2.6 on 2025-11-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '4.\xa0Chapters'},
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_images/'),
        ),
        migrations.AddField(
            model_name='teacherstudentchat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
