# Generated by Django 5.2.6 on 2025-12-02 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_chapter_options_student_image_teacher_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherstudentchat',
            options={'verbose_name_plural': '17. ChatBot'},
        ),
        migrations.AddField(
            model_name='teacherstudentchat',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherstudentchat',
            name='msg_type',
            field=models.CharField(default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherstudentchat',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
