# Generated by Django 5.2.6 on 2025-12-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_teacherstudentchat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstudentchat',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacherstudentchat'),
        ),
    ]
