# Generated by Django 5.2.6 on 2025-12-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_is_approved_teacher_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_approved',
        ),
    ]
