# Generated by Django 5.2.6 on 2025-12-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_student_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='default123', max_length=100),
            preserve_default=False,
        ),
    ]
