# Generated by Django 5.2.6 on 2025-12-13 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_student_is_approved_teacher_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptquiz',
            options={'verbose_name_plural': 'Attempted Questions'},
        ),
        migrations.AlterUniqueTogether(
            name='attemptquiz',
            unique_together={('student', 'quiz', 'question')},
        ),
        migrations.AddField(
            model_name='attemptquiz',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attemptquiz',
            name='selected_answer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestions'),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.RemoveField(
            model_name='attemptquiz',
            name='right_ans',
        ),
    ]
