# Generated by Django 5.2.6 on 2025-12-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_attemptquiz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptquiz',
            options={'verbose_name_plural': 'Attempted Questions'},
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='selected_answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='attemptquiz',
            unique_together={('student', 'quiz', 'question')},
        ),
    ]
