# Generated by Django 5.2.6 on 2025-12-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_attemptquiz_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptquiz',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
