# Generated by Django 5.2.6 on 2025-12-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_attemptquiz_selected_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptquiz',
            options={'verbose_name_plural': '14. Attempted Questions '},
        ),
        migrations.AlterUniqueTogether(
            name='attemptquiz',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attemptquiz',
            name='right_ans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestions'),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.RemoveField(
            model_name='attemptquiz',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='attemptquiz',
            name='selected_answer',
        ),
    ]
