# Generated by Django 5.2.6 on 2025-12-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_attemptquiz_options_alter_attemptquiz_question_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attemptquiz',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestions'),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='right_ans',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
