# Generated by Django 5.2.6 on 2025-12-13 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_attemptquiz_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptquiz',
            options={'verbose_name_plural': '14. Attempted Questions '},
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestions'),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='right_ans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attemptquiz',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
