# Generated by Django 5.2.6 on 2025-12-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_attemptquiz_options_alter_attemptquiz_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptquiz',
            options={'verbose_name_plural': '14. Attempted Questions'},
        ),
        migrations.AddField(
            model_name='attemptquiz',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='attemptquiz',
            unique_together={('student', 'quiz')},
        ),
    ]
