# Generated by Django 5.2.6 on 2025-12-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_attemptquiz_options_attemptquiz_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquiz',
            name='selected_answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
