# Generated by Django 5.2.6 on 2025-12-15 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_attemptquiz_selected_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('workshop', 'Workshop'), ('bootcamp', 'Bootcamp')], max_length=20)),
                ('date', models.DateField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_seats', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('college_or_school', models.CharField(blank=True, max_length=200)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workshop')),
            ],
        ),
    ]
