# Generated by Django 5.2.6 on 2025-12-16 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_workshop_workshopregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherstudentchat',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Individual Chats'},
        ),
        migrations.RenameField(
            model_name='teacherstudentchat',
            old_name='msg_to',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='teacherstudentchat',
            old_name='msg_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='teacherstudentchat',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='teacherstudentchat',
            name='msg_from',
        ),
        migrations.RemoveField(
            model_name='teacherstudentchat',
            name='msg_type',
        ),
        migrations.RemoveField(
            model_name='teacherstudentchat',
            name='parent_group',
        ),
        migrations.AddField(
            model_name='teacherstudentchat',
            name='sender',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='teacher', max_length=10),
        ),
        migrations.CreateModel(
            name='CourseChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name_plural': 'Course Chat Groups',
            },
        ),
        migrations.CreateModel(
            name='CourseGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursechatgroup')),
                ('sender_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
            options={
                'verbose_name_plural': 'Group Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
