# Generated by Django 5.2.6 on 2025-12-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_teacherstudentchat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherstudentchat',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddIndex(
            model_name='teacherstudentchat',
            index=models.Index(fields=['teacher', 'student', 'sender', 'is_read'], name='main_teache_teacher_972e48_idx'),
        ),
    ]
