# Generated by Django 5.2.6 on 2025-12-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_teacherstudentchat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstudentchat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='teacherstudentchat',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
