# Generated by Django 5.2.6 on 2025-12-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_teacherstudentchat_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(max_length=200, null=True, upload_to='chapter_videos/'),
        ),
    ]
