# Generated by Django 5.2.6 on 2025-12-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_student_created_at_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attemptquiz',
            unique_together={('student', 'quiz', 'question')},
        ),
        migrations.RemoveField(
            model_name='attemptquiz',
            name='right_ans',
        ),
    ]
