# Generated by Django 5.2.6 on 2026-01-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_attemptquiz_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopregistration',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='workshopregistration',
            name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
