# Generated by Django 5.2.6 on 2026-01-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_workshopregistration_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='payable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
