# Generated by Django 5.2.10 on 2026-01-23 10:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('status', models.CharField(default='issued', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Student Certificates',
            },
        ),
        migrations.CreateModel(
            name='StudentChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Student Chapter Progress',
            },
        ),
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'verbose_name_plural': 'Student Assignments'},
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='submitted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_files/'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='assignment_images/'),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='certificate_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='certificate_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='student_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
        migrations.AddConstraint(
            model_name='studentfavoritecourse',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='unique_favorite_course'),
        ),
        migrations.AddField(
            model_name='studentcertificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='main.course'),
        ),
        migrations.AddField(
            model_name='studentcertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='main.student'),
        ),
        migrations.AddField(
            model_name='studentchapterprogress',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='main.chapter'),
        ),
        migrations.AddField(
            model_name='studentchapterprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to='main.student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcertificate',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='studentchapterprogress',
            unique_together={('student', 'chapter')},
        ),
    ]
