# Generated by Django 5.2.10 on 2026-02-09 09:07

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_studentcertificate_studentchapterprogress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopregistration',
            name='college_or_school',
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('school', 'School'), ('college', 'College')], max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('type'), name='unique_institution_name_type')],
            },
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main.institution'),
        ),
    ]
