# Generated by Django 5.2.10 on 2026-02-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_workshopregistration_college_or_school_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseenrollment',
            unique_together={('course', 'student')},
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='is_completed',
        ),
    ]
