# Generated by Django 5.2.10 on 2026-02-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_studentcourseenrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
