# Generated by Django 5.2.10 on 2026-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_studentcourseenrollment_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestions',
            options={'verbose_name_plural': '12. Quiz Questions'},
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='coding_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='coding_starter_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('coding', 'Coding')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='ans1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='ans2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='ans3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='ans4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='questions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='right_ans',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
